name: gd_store
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  build_runner: ^2.4.11
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.7
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.2
  riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
